apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    app: san-tomcat-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: san-tomcat-deploy
  template:
    metadata:
      labels:
        app: san-tomcat-deploy
    spec:
      containers:
      - name: sanjay-tomcat-container
        image: sanjaysan01/tomcat-webappimg:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sanjay-np-service
  labels:
    app: san-tomcat-deploy
spec:
  selector:
    app: san-tomcat-deploy

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
