apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    app: tomcat-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-webapp
  template:
    metadata:
      labels:
        app: tomcat-webapp
    spec:
      containers:
      - name: tomcat-container
        image: sanjaysan01/tomcat-webappimg:9
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sanjay-tomcat-np-service
  labels:
    app: tomcat-webapp
spec:
  selector:
    app: tomcat-webapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
